import LegalPage from "@/components/LegalPage";

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="16 August 2026">
      <p>
        Scout Program Builder is an independent planning tool and is not affiliated with,
        endorsed by, or associated with Scouts Australia or any official Scouts organisation.
        By using this app, you agree to the following terms.
      </p>

      <h2>Purpose of the app</h2>
      <p>
        Scout Program Builder is provided to help youth group leaders plan terms, generate run
        sheets, and track member progress. It is a planning aid only and does not replace your
        organisation&apos;s official program materials, policies, or guidance.
      </p>

      <h2>Program framework references</h2>
      <p>
        All Scouts Australia program framework references (OAS, milestones, challenge areas) are
        used for informational purposes only and are the property of their respective
        organisation.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Run sheets, activities, and topic suggestions generated by the app&apos;s AI features are
        starting points only. Leaders are responsible for reviewing all generated content for
        accuracy, safety, and suitability before using it with a group.
      </p>

      <h2>Your responsibilities</h2>
      <p>
        You are responsible for the accuracy of information you enter, for complying with your
        organisation&apos;s policies, and for obtaining any consents required before entering
        information about children or young people.
      </p>

      <h2>No warranty</h2>
      <p>
        The app is provided &quot;as is&quot; without warranty of any kind. We are not liable for
        any loss or damage arising from your use of the app or reliance on generated content.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these terms from time to time. Continued use of the app after changes are
        posted constitutes acceptance of the updated terms.
      </p>
    </LegalPage>
  );
}
